# Generated by Django 5.2.1 on 2025-05-17 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_user_id', models.BigIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=500)),
                ('deadline', models.DateTimeField()),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
